name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List directory contents
        run: ls -l

      - name: Debug info
        run: |
          pwd
          echo "Zawartość katalogu app-apache:"
          ls -l app-apache

      - name: Deploy to EC2
        run: |
          cd app-apache  # Dostosowano do poprawnego poziomu katalogu
          chmod +x script.sh  # Upewnij się, że script.sh ma odpowiednie uprawnienia
          ./script.sh
